# 🏳️‍⚧️ Trans-Pride Kitty Terminal Theme

# Special Colors
foreground            #E4E7ED
background            #111218
selection_foreground  #111218
selection_background  #F7A8B8
cursor                #F7A8B8
cursor_text_color     #111218

# URL underline color
url_color             #5BCEFA

# Window borders
active_border_color   #F7A8B8
inactive_border_color #262936

# Tab bar colors
active_tab_foreground   #111218
active_tab_background   #F7A8B8
inactive_tab_foreground #8290A8
inactive_tab_background #191B24

# The ANSI 16 colors
color0 #111218
color8 #8290A8

color1 #E88388
color9 #F7A8B8

color2  #A3BE8C
color10 #C2D6B2

color3  #F6E088
color11 #F6E088

color4  #5BCEFA
color12 #5BCEFA

color5  #B48EAD
color13 #D1B8CC

color6  #5BCEFA
color14 #B9E3E9

color7  #E4E7ED
color15 #FFFFFF